name: Release
on:
  pull_request:
  push:
    branches: [master]
  release:
    types: [published]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      if: ${{ github.event_name == 'push' || github.event_name == 'release' }}
      with:
        repository: intoto/verifier
        tag_with_ref: true
        dockerfile: Dockerfiles/in-toto-verify.Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
